enhancement:
  - head-branch: ['^feat/', '^feature/']

bug:
  - head-branch: ['^fix/', '^bugfix/', '^hotfix/']

docs:
  - head-branch: ['^docs/']

chore:
  - head-branch: ['^chore/']

skip-release-notes:
  - head-branch: [^chore/release-']

ci:
  - head-branch: ['^ci/']

refactor:
  - head-branch: ['^refactor/']

test:
  - head-branch: ['^test/']

dependencies:
  - head-branch: ['^deps/', '^dependabot/']
